# Generated by Django 5.0.14 on 2026-09-05 09:21

import django.db.models.deletion
import ops.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('READ_ONLY', 'Read only'), ('SECURITY_LOCKED', 'Security locked')], default='ACTIVE', max_length=20)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('max_users', models.PositiveIntegerField(default=25)),
                ('max_teams', models.PositiveIntegerField(default=5)),
                ('max_projects', models.PositiveIntegerField(default=10)),
                ('max_tasks', models.PositiveIntegerField(default=10000)),
                ('max_attachment_bytes', models.PositiveBigIntegerField(default=2147483648)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=120)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=80)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ops.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('purpose', models.TextField(max_length=2000)),
                ('expected_users', models.PositiveIntegerField(default=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('MORE_INFO', 'More information required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('decision_reason', models.TextField(blank=True, max_length=2000)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_decisions', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('visibility', models.CharField(choices=[('SUMMARY', 'Summarized'), ('FULL', 'Full detail')], default='SUMMARY', max_length=10)),
                ('client_leave_approval', models.BooleanField(default=False)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('working_days', models.JSONField(default=ops.models.default_working_days)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='ops.organization')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('leave_type', models.CharField(max_length=40)),
                ('reason', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('PENDING_LEAD', 'Pending team lead'), ('PENDING_CLIENT', 'Pending client'), ('CHANGES_REQUIRED', 'Changes required'), ('APPROVED', 'Approved'), ('UNAPPROVED', 'Unapproved leave'), ('AUTO_APPROVED', 'Backdated - system approved'), ('CANCELLED', 'Cancelled')], default='PENDING_LEAD', max_length=24)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='ops.organization')),
                ('affected_projects', models.ManyToManyField(related_name='leave_requests', to='ops.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('CLIENT', 'Client'), ('CLIENT_APPROVER', 'Client approver')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='ops.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(max_length=10000)),
                ('acceptance_criteria', models.TextField(blank=True, max_length=10000)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('BLOCKED', 'Blocked'), ('REVIEW', 'Review'), ('UAT', 'UAT'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NOT_STARTED', max_length=20)),
                ('assignment_status', models.CharField(choices=[('UNASSIGNED', 'Unassigned'), ('PENDING', 'Pending member action'), ('OVERDUE', 'Pending member action - overdue'), ('ACCEPTED', 'Accepted')], default='UNASSIGNED', max_length=16)),
                ('review_required', models.BooleanField(default=False)),
                ('complexity', models.PositiveSmallIntegerField(default=1)),
                ('planned_start', models.DateTimeField(blank=True, null=True)),
                ('forecast_finish', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ops.project')),
            ],
        ),
        migrations.CreateModel(
            name='Blocker',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=5000)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('resolution', models.TextField(blank=True, max_length=5000)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_blockers', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_blockers', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raised_blockers', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockers', to='ops.task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_revision', models.PositiveIntegerField(default=1)),
                ('outcome', models.CharField(max_length=40)),
                ('notes', models.TextField(blank=True, max_length=5000)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ops.task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskTester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_main', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testers', to='ops.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testing_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='ops.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='ops.team'),
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='ops.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UATObservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(max_length=10000)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FIXING', 'Fix in progress'), ('READY', 'Ready for retest'), ('RETESTING', 'Retesting'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('DUPLICATE', 'Duplicate')], default='OPEN', max_length=16)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_observations', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_observations', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='ops.task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('OWNER', 'Organization owner'), ('ADMIN', 'Organization administrator'), ('MANAGEMENT', 'Senior management'), ('MEMBER', 'Team member'), ('CLIENT', 'Client')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='ops.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='ops_members_user_id_6aebc1_idx'), models.Index(fields=['organization', 'role'], name='ops_members_organiz_eba193_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='unique_org_membership'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['organization', 'created_at'], name='ops_auditev_organiz_c748d4_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor', 'created_at'], name='ops_auditev_actor_i_4c3f0f_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmembership',
            index=models.Index(fields=['user', 'is_active'], name='ops_project_user_id_8cc7c4_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmembership',
            index=models.Index(fields=['project', 'role'], name='ops_project_project_4eed71_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='unique_project_membership'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='ops_task_project_37e6bc_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee', 'status'], name='ops_task_assigne_4c0279_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('project', 'sequence'), name='unique_task_sequence'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('complexity__gte', 1), ('complexity__lte', 5)), name='task_complexity_1_to_5'),
        ),
        migrations.AddConstraint(
            model_name='tasktester',
            constraint=models.UniqueConstraint(fields=('task', 'user'), name='unique_task_tester'),
        ),
        migrations.AddConstraint(
            model_name='tasktester',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('task',), name='one_main_tester_per_task'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_team_name_in_org'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'is_active'], name='ops_project_organiz_8bbb01_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['team', 'is_active'], name='ops_project_team_id_9a10ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_project_code_in_org'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(fields=('team', 'user'), name='unique_team_member'),
        ),
    ]
