# Generated by Django 5.0.14 on 2026-09-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_clientaccount_project_client_clientmembership_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformEmailSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('host', models.CharField(blank=True, max_length=253)),
                ('port', models.PositiveIntegerField(default=587)),
                ('username', models.CharField(blank=True, max_length=254)),
                ('password_encrypted', models.TextField(blank=True)),
                ('security', models.CharField(choices=[('STARTTLS', 'STARTTLS'), ('SSL', 'SSL')], default='STARTTLS', max_length=8)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
