import React, { useMemo, useState } from 'react';

const tasks = [
  ['QOP-148','Client workspace permissions','Ananya S.','Today','In progress','blue'],
  ['QOP-151','Leave calendar import validation','Karan M.','Sep 8','Review','violet'],
  ['QOP-144','Project health summary','Meera R.','Sep 9','Not started','neutral'],
  ['QOP-139','UAT observation workflow','Dev P.','Sep 10','UAT','amber'],
];
const Mark=({small=false})=><span className={'mark '+(small?'small':'')}>BQ</span>;

function Public({launch}){return <div>
  <header className="public-nav"><a className="brand" href="#top"><Mark/>BQ Labs</a><nav><a href="#product">Quantum OPS</a><a href="#approach">Approach</a><a href="#trust">Trust</a></nav><button className="button quiet" onClick={launch}>Sign in</button></header>
  <main id="top"><section className="hero"><span className="eyebrow">BQ Labs introduces Quantum OPS</span><h1>Operational clarity.<br/><em>Designed for everyone.</em></h1><p>One calm workspace for teams and clients to plan work, surface risks, approve leave, and understand progress without chasing updates.</p><div className="hero-actions"><button className="button primary" onClick={launch}>Open Quantum OPS</button><a href="#product">Explore the platform →</a></div><ProductPreview/></section>
  <section className="features" id="product"><div className="section-copy"><span className="eyebrow">One shared source of truth</span><h2>Work moves forward when context is visible.</h2><p>Assignments become commitments. Progress stays current. Reviews and UAT have a clear owner. Clients see exactly the level of detail each project permits.</p></div><div className="feature-grid">{[['01','Plan with confidence','Project calendars, milestones, dependencies, and ownership create an achievable plan.'],['02','Act with clarity','Role-aware queues show every person what needs a decision, without exposing unrelated work.'],['03','Deliver transparently','Evidence, reviews, UAT observations, and immutable audit trails keep delivery accountable.']].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
  <section className="story" id="approach"><div><span className="eyebrow">From request to result</span><h2>A workflow that reflects how professional teams actually operate.</h2></div><ol>{[['Assign','The working team member accepts responsibility.'],['Deliver','Status, blockers, and forecasts stay visible.'],['Verify','Reviewers and accepted testers record evidence.'],['Close','Completion gates protect quality and trust.']].map(x=><li key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></li>)}</ol></section>
  <section className="trust" id="trust"><div><span className="eyebrow">Security by architecture</span><h2>Your organization’s work stays inside its boundaries.</h2></div><div>{[['Project-scoped access','Clients only see projects explicitly assigned to them.'],['Server-side authorization','Every protected operation is verified at the API, never only in the interface.'],['Accountable actions','Important changes create immutable, attributable audit events.']].map(x=><p key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></p>)}</div></section></main>
  <footer><a className="brand" href="#top"><Mark/>BQ Labs</a><p>Thoughtful software for modern operations.</p><span>© 2026 BQ Labs</span></footer>
</div>}

function ProductPreview(){return <div className="preview"><div className="preview-top"><b><Mark small/> Quantum OPS</b><span>Search tasks, people, projects…</span><i>AR</i></div><div className="preview-body"><aside><b>Overview</b><span>My work</span><span>Projects</span><span>People</span><span>Leave</span></aside><div className="preview-main"><small>MONDAY, 7 SEPTEMBER</small><h3>Good morning, Aarav.</h3><p>Here’s what needs your attention.</p><div className="preview-stats"><div><b>8</b><span>Tasks in progress</span></div><div><b>3</b><span>Awaiting action</span></div><div><b>92%</b><span>On-time delivery</span></div></div><div className="preview-panels"><div><b>Project health</b><i>On track</i><div className="meter"><span/></div><small>Quantum OPS · 68% complete</small></div><div><b>Next up</b><p>Review access-control matrix</p><small>Due today · High priority</small></div></div></div></div></div>}

function Dashboard({exit}){const [active,setActive]=useState('Overview');const [query,setQuery]=useState('');const shown=useMemo(()=>tasks.filter(t=>t.join(' ').toLowerCase().includes(query.toLowerCase())),[query]);return <div className="app-shell"><aside className="sidebar"><div className="app-brand"><Mark/><span><b>Quantum</b> OPS</span></div><div className="workspace"><i>BQ</i><span><b>BQ Labs</b><small>Team workspace</small></span>⌄</div><nav>{['Overview','My work','Projects','UAT & review','Leave','People'].map((x,i)=><button className={active===x?'active':''} onClick={()=>setActive(x)} key={x}><i>{['⌂','✓','▦','◎','◇','♙'][i]}</i>{x}{x==='UAT & review'&&<em>4</em>}</button>)}</nav><div className="side-bottom"><button>⚙ Settings</button><button onClick={exit}>↗ BQ Labs site</button><div className="user"><i>AR</i><span><b>Aarav Rao</b><small>Team lead</small></span>•••</div></div></aside>
  <div className="app-main"><header className="app-top"><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tasks, people, projects…"/><kbd>⌘ K</kbd></label><div><button>◐</button><button>♢</button><i>AR</i></div></header><main className="dashboard"><div className="welcome"><div><small>MONDAY, 7 SEPTEMBER</small><h1>{active==='Overview'?'Good morning, Aarav.':active}</h1><p>{active==='Overview'?`Here’s what needs your attention across Quantum OPS.`:`Your ${active.toLowerCase()} workspace, scoped to accessible projects.`}</p></div><button className="button primary">＋ Create task</button></div>
  <section className="metrics">{[['Tasks in progress','8','+3 this week','blue'],['Awaiting your action','3','2 assignments · 1 review','violet'],['Open blockers','2','1 high priority','amber'],['Delivery confidence','92%','On track','green']].map(x=><article key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small className={x[3]}>{x[2]}</small></article>)}</section>
  <section className="dashboard-grid"><article className="panel tasks"><PanelHead title="Priority work" sub="Tasks that need attention soon." action="View all →"/><div className="task-head"><span>Task</span><span>Owner</span><span>Due</span><span>Status</span></div>{shown.map(t=><div className="task-row" key={t[0]}><div><small>{t[0]} · Quantum OPS</small><b>{t[1]}</b></div><span>{t[2]}</span><span>{t[3]}</span><i className={t[5]}>{t[4]}</i></div>)}</article>
  <article className="panel attention"><PanelHead title="Needs attention" sub="Decisions waiting on you."/>{[['✓','Accept assignment','Project health summary','Review'],['◎','UAT retest ready','Client export permissions','Open'],['◇','Leave approval','Priya · Sep 14–15','Review']].map(x=><div className="attention-row" key={x[1]}><i>{x[0]}</i><span><b>{x[1]}</b><small>{x[2]}</small></span><button>{x[3]}</button></div>)}</article>
  <article className="panel project"><PanelHead title="Project health" sub="Delivery confidence at a glance." action="Open project →"/><div className="project-name"><i>Q</i><span><b>Quantum OPS</b><small>QOP · Product development</small></span><em>On track</em></div><p><span>Overall progress</span><b>68%</b></p><div className="meter"><span/></div><div className="project-stats">{[['24','Completed'],['8','In progress'],['4','Remaining'],['18 Sep','Next milestone']].map(x=><span key={x[1]}><b>{x[0]}</b><small>{x[1]}</small></span>)}</div></article>
  <article className="panel team"><PanelHead title="Team availability" sub="Today across your project." action="Calendar →"/><div className="avatars"><span>AS</span><span>KM</span><span>MR</span><span>DP</span><span>+3</span><b>7 available</b></div><div className="leave-note">◇ <span><b>2 upcoming leaves</b><small>Next: Priya on Sep 14</small></span></div></article></section></main></div><nav className="mobile-nav">{['Overview','My work','Projects','Leave'].map(x=><button onClick={()=>setActive(x)} className={active===x?'active':''} key={x}>{x}</button>)}</nav></div>}
function PanelHead({title,sub,action}){return <div className="panel-head"><span><h2>{title}</h2><p>{sub}</p></span>{action&&<button>{action}</button>}</div>}
export default function App(){const [app,setApp]=useState(location.hash==='#app');const launch=()=>{location.hash='app';setApp(true)};const exit=()=>{location.hash='';setApp(false)};return app?<Dashboard exit={exit}/>:<Public launch={launch}/>}
