import React, { useEffect, useMemo, useState } from 'react';

const Q='/quantum-ops';
const navItems=[['dashboard','Overview'],['tasks','My tasks'],['uat','UAT & observations'],['leave','Leave & comp off'],['setup','Workspace setup']];

function go(path){history.pushState({},'',path);window.dispatchEvent(new PopStateEvent('popstate'))}
function usePath(){const [path,setPath]=useState(location.pathname);useEffect(()=>{const f=()=>setPath(location.pathname);addEventListener('popstate',f);return()=>removeEventListener('popstate',f)},[]);return path}
function cookie(name){return document.cookie.split('; ').find(x=>x.startsWith(name+'='))?.split('=').slice(1).join('=')||''}
async function api(path,options={}){if(!cookie('csrftoken'))await fetch('/api/auth/csrf/',{credentials:'same-origin'});const response=await fetch('/api/'+path,{credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRFToken':decodeURIComponent(cookie('csrftoken')),...options.headers},...options});let data=null;try{data=await response.json()}catch{}if(!response.ok){const message=data?.detail||data?.non_field_errors?.[0]||Object.values(data||{}).flat()[0]||'Something went wrong.';throw Object.assign(new Error(message),{status:response.status,data})}return data}
const Mark=()=> <span className="mark">BQ</span>;

function Public(){return <div className="public"><header className="public-nav"><a className="brand" href="/" onClick={e=>{e.preventDefault();go('/')}}><Mark/>BQ Labs</a><nav><a href="#product">Quantum OPS</a><a href="#trust">Trust</a></nav><button className="button quiet" onClick={()=>go(Q+'/login')}>Sign in</button></header><main><section className="hero"><span className="eyebrow">BQ Labs introduces Quantum OPS</span><h1>Operational clarity.<br/><em>Designed for everyone.</em></h1><p>A secure workspace for teams and clients to plan work, test delivery, manage availability, and understand progress without chasing updates.</p><div className="hero-actions"><button className="button primary" onClick={()=>go(Q+'/login')}>Sign in to Quantum OPS</button><button className="link-button" onClick={()=>go(Q+'/register')}>Create your workspace →</button></div><div className="security-note"><b>Private by default</b><span>Project data is available only after authentication and server-side authorization.</span></div></section><section className="features" id="product"><div><span className="eyebrow">One operating picture</span><h2>From assignment to verified delivery.</h2></div><div className="feature-grid">{[['01','Plan','Create clients, projects, teams, calendars, and accountable tasks.'],['02','Deliver','Members accept work and keep progress, risks, and forecasts current.'],['03','Verify','Accepted testers raise observations and protect completion quality.']].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section><section className="trust" id="trust"><span className="eyebrow">Security is foundational</span><h2>No login. No workspace.</h2><p>Direct dashboard links return to sign-in. Client, project, task, testing, and leave permissions are enforced by the API, not trusted to the browser.</p></section></main><footer><span className="brand"><Mark/>BQ Labs</span><span>© 2026 BQ Labs</span></footer></div>}

function Auth({register=false}){const [step,setStep]=useState(1),[form,setForm]=useState({email:'',password:'',first_name:'',last_name:'',otp:''}),[busy,setBusy]=useState(false),[error,setError]=useState('');const update=e=>setForm({...form,[e.target.name]:e.target.value});const destination=()=>{const value=new URLSearchParams(location.search).get('return_to');return value?.startsWith(Q+'/')?value:(register?Q+'/setup':Q+'/dashboard')};async function submit(e){e.preventDefault();setBusy(true);setError('');try{if(!register){await api('auth/login/',{method:'POST',body:JSON.stringify({email:form.email,password:form.password})});go(destination())}else if(step===1){await api('auth/registration-otp/',{method:'POST',body:JSON.stringify({email:form.email,challenge_token:window.turnstileToken||'development'})});setStep(2)}else{await api('auth/register/',{method:'POST',body:JSON.stringify(form)});go(destination())}}catch(err){setError(err.message)}finally{setBusy(false)}}return <div className="auth-page"><a className="brand auth-brand" href="/" onClick={e=>{e.preventDefault();go('/')}}><Mark/>BQ Labs</a><div className="auth-card"><div className="auth-intro"><span className="product-lock">Q</span><h1>{register?'Create your workspace':'Welcome back'}</h1><p>{register?(step===1?'Verify your work email to begin.':'Enter the code we sent and secure your account.'):'Sign in to access your authorized Quantum OPS workspace.'}</p></div><form onSubmit={submit}>{register&&step===2&&<div className="two"><label>First name<input required name="first_name" value={form.first_name} onChange={update}/></label><label>Last name<input required name="last_name" value={form.last_name} onChange={update}/></label></div>}<label>Email address<input required type="email" autoComplete="email" name="email" value={form.email} onChange={update} readOnly={register&&step===2}/></label>{(!register||step===2)&&<label>Password<input required minLength="10" type="password" autoComplete={register?'new-password':'current-password'} name="password" value={form.password} onChange={update}/></label>}{register&&step===2&&<label>Six-digit verification code<input required inputMode="numeric" pattern="[0-9]{6}" maxLength="6" name="otp" value={form.otp} onChange={update}/></label>}{error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary full" disabled={busy}>{busy?'Please wait…':register?(step===1?'Send verification code':'Create account'):'Sign in securely'}</button></form><p className="auth-switch">{register?'Already registered?':'New to Quantum OPS?'} <button onClick={()=>go(register?Q+'/login':Q+'/register')}>{register?'Sign in':'Create a workspace'}</button></p></div><p className="auth-foot">Protected by encrypted sessions, CSRF controls, throttling, and project-scoped authorization.</p></div>}

function Protected({page}){const [state,setState]=useState({loading:true,user:null});useEffect(()=>{api('auth/session/').then(user=>setState({loading:false,user})).catch(()=>go(Q+'/login'))},[]);if(state.loading)return <div className="loading"><Mark/><span>Verifying your session…</span></div>;return <Shell user={state.user} page={page}/>}
function Shell({user,page}){const links=user.is_staff?[...navItems,['admin','Platform admin']]:navItems;async function logout(){await api('auth/logout/',{method:'POST'});go(Q+'/login')}return <div className="app-shell"><aside className="sidebar"><div className="app-brand"><Mark/><span><b>Quantum</b> OPS</span></div><nav>{links.map(x=><button className={page===x[0]?'active':''} onClick={()=>go(Q+'/'+x[0])} key={x[0]}>{x[1]}</button>)}</nav><div className="side-bottom"><div className="user"><i>{(user.first_name?.[0]||user.email[0]).toUpperCase()}</i><span><b>{[user.first_name,user.last_name].filter(Boolean).join(' ')||user.email}</b><small>{user.email}</small></span></div><button onClick={logout}>Sign out</button></div></aside><div className="app-main"><header className="app-top"><button className="mobile-brand" onClick={()=>go(Q+'/dashboard')}><Mark/>Quantum OPS</button><span>{user.is_staff?'BQ Labs administration':'Secure workspace'}</span><button onClick={logout}>Sign out</button></header><main className="dashboard">{page==='admin'?<PlatformAdmin user={user}/>:page==='setup'?<Setup user={user}/>:page==='tasks'?<Tasks user={user}/>:page==='uat'?<UAT user={user}/>:page==='leave'?<Leave/>:<Overview user={user}/>}</main></div><nav className="mobile-nav">{navItems.slice(0,4).map(x=><button className={page===x[0]?'active':''} onClick={()=>go(Q+'/'+x[0])} key={x[0]}>{x[1]}</button>)}</nav></div>}

function useLoad(loader,deps=[]){const [state,setState]=useState({loading:true,data:null,error:''});useEffect(()=>{let live=true;setState(s=>({...s,loading:true}));loader().then(data=>live&&setState({loading:false,data,error:''})).catch(e=>live&&setState({loading:false,data:null,error:e.message}));return()=>{live=false}},deps);return state}
const list=x=>x?.results||x||[];
function Overview({user}){const state=useLoad(async()=>Promise.all([api('organizations/'),api('clients/'),api('projects/'),api('tasks/'),api('uat-observations/'),api('leave/')]),[]);if(state.loading)return <PageLoading/>;if(state.error)return <Empty title="Unable to load your workspace" text={state.error}/>;const [orgs,clients,projects,tasks,uat,leave]=state.data.map(list);if(!orgs.length)return <Empty title="Create your first workspace" text="Set up your organization, first client, team, and project before assigning work." action="Start setup" onAction={()=>go(Q+'/setup')}/>;const assigned=tasks.filter(t=>t.assignee===user.id);return <><PageTitle kicker="Your work today" title={`Good morning, ${user.first_name||'there'}.`} text="Everything shown here is filtered by your authenticated access." action="Create task" onAction={()=>go(Q+'/tasks')}/><section className="metrics">{[['My tasks',assigned.length],['Accessible projects',projects.length],['Open observations',uat.filter(x=>!['RESOLVED','REJECTED','DUPLICATE'].includes(x.status)).length],['Leave requests',leave.length]].map(x=><article key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></article>)}</section><section className="dashboard-grid"><article className="panel wide"><PanelHead title="My current tasks" action="View tasks" onAction={()=>go(Q+'/tasks')}/>{tasks.length?<TaskRows tasks={tasks.slice(0,6)} user={user}/>:<InlineEmpty text="No task has been assigned to you yet."/>}</article><article className="panel"><PanelHead title="Workspace structure"/><div className="summary-list"><p><b>{orgs.length}</b><span>Workspace</span></p><p><b>{clients.length}</b><span>Clients</span></p><p><b>{projects.length}</b><span>Projects</span></p></div></article></section></>}

function Setup(){
  const [tick,setTick]=useState(0),[form,setForm]=useState({}),[error,setError]=useState('');
  const state=useLoad(async()=>({orgs:list(await api('organizations/')),clients:list(await api('clients/')),teams:list(await api('teams/')),projects:list(await api('projects/'))}),[tick]);
  if(state.loading)return <PageLoading/>;
  const d=state.data||{orgs:[],clients:[],teams:[],projects:[]};
  const stage=!d.orgs.length?'workspace':!d.clients.length?'client':!d.teams.length?'team':'project';
  async function submit(e){e.preventDefault();setError('');try{
    if(stage==='workspace')await api('organizations/',{method:'POST',body:JSON.stringify({name:form.name,timezone:'Asia/Kolkata'})});
    if(stage==='client')await api('clients/',{method:'POST',body:JSON.stringify({organization:d.orgs[0].id,name:form.name,code:slug(form.name)})});
    if(stage==='team')await api('teams/',{method:'POST',body:JSON.stringify({organization:d.orgs[0].id,name:form.name})});
    if(stage==='project')await api('projects/',{method:'POST',body:JSON.stringify({client:d.clients[0].id,team:d.teams[0].id,name:form.name,code:(form.code||slug(form.name)).toUpperCase().slice(0,20),description:form.description||'',visibility:'SUMMARY',working_days:[0,1,2,3,4]})});
    setForm({});setTick(x=>x+1)
  }catch(e){setError(e.message)}}
  return <><PageTitle kicker="Guided setup" title="Build your operating workspace." text="Workspace → client → team → projects. You remain in control of who joins each scope."/><div className="setup-steps">{['workspace','client','team','project'].map((x,i)=><span className={x===stage?'active':(['workspace','client','team','project'].indexOf(stage)>i?'done':'')} key={x}>{i+1}. {x}</span>)}</div><div className="dashboard-grid"><section className="panel setup-card"><h2>{stage==='workspace'?'Name your workspace':stage==='client'?'Add your first client':stage==='team'?'Create the delivery team':'Add a client project'}</h2><p>{stage==='workspace'?'For example, your company or independent consulting practice.':stage==='client'?'For example, TALIC.':stage==='team'?'For example, TALIC Operations Team.':'For example, CAMS or Operations – Agent Payout.'}</p><form onSubmit={submit}><label>{stage==='project'?'Project name':'Name'}<input required value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})}/></label>{stage==='project'&&<><label>Project code<input required maxLength="20" value={form.code||''} onChange={e=>setForm({...form,code:e.target.value})}/></label><label>Description<textarea value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></label></>}{error&&<p className="form-error">{error}</p>}<button className="button primary">{stage==='project'?'Create project':'Continue'}</button></form>{d.projects.length>0&&<button className="link-button done-link" onClick={()=>go(Q+'/dashboard')}>Go to dashboard →</button>}</section>{d.projects.length>0&&<InvitePanel data={d}/>}</div></>
}
function InvitePanel({data}){const [form,setForm]=useState({email:'',project:data.projects[0]?.id||'',role:'MEMBER'}),[message,setMessage]=useState(''),[error,setError]=useState('');async function submit(e){e.preventDefault();setError('');setMessage('');try{await api('invitations/',{method:'POST',body:JSON.stringify({organization:data.orgs[0].id,client:data.clients[0].id,project:form.project,scope:'PROJECT',email:form.email,role:form.role})});setMessage('Invitation sent securely.');setForm({...form,email:''})}catch(e){setError(e.message)}}return <section className="panel"><PanelHead title="Invite a project member"/><p className="helper">Invite a colleague after creating the project. They must sign in with the same verified email.</p><form onSubmit={submit}><label>Email address<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Project<select value={form.project} onChange={e=>setForm({...form,project:e.target.value})}>{data.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Access<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="MEMBER">Team member or tester</option><option value="CLIENT">Client viewer</option><option value="CLIENT_APPROVER">Client approver</option></select></label>{message&&<p className="form-success">{message}</p>}{error&&<p className="form-error">{error}</p>}<button className="button primary full">Send invitation</button></form></section>}
function slug(x=''){return x.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)}

function Tasks({user}){
  const [refresh,setRefresh]=useState(0),[form,setForm]=useState({title:'',description:'',project:'',assignee:''}),[error,setError]=useState('');
  const state=useLoad(async()=>({tasks:list(await api('tasks/')),projects:list(await api('projects/')),members:list(await api('project-members/'))}),[refresh]);
  if(state.loading)return <PageLoading/>;
  const eligible=state.data.members.filter(m=>String(m.project)===String(form.project)&&m.role==='MEMBER'&&m.is_active);
  async function submit(e){e.preventDefault();setError('');try{await api('tasks/',{method:'POST',body:JSON.stringify({...form,assignee:form.assignee||null,complexity:1})});setForm({title:'',description:'',project:'',assignee:''});setRefresh(x=>x+1)}catch(e){setError(e.message)}}
  return <><PageTitle kicker="Authenticated work queue" title="My tasks" text="Members see only tasks they own, are assigned, or are testing. Leads see their authorized project workload."/><section className="dashboard-grid"><article className="panel wide"><PanelHead title="Current tasks"/>{state.data.tasks.length?<TaskRows tasks={state.data.tasks} user={user} refresh={()=>setRefresh(x=>x+1)}/>:<InlineEmpty text="No tasks are currently visible to you."/>}</article><article className="panel"><PanelHead title="Create and assign task"/><form onSubmit={submit}><label>Project<select required value={form.project} onChange={e=>setForm({...form,project:e.target.value,assignee:''})}><option value="">Select project</option>{state.data.projects.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></label><label>Assign to<select value={form.assignee} onChange={e=>setForm({...form,assignee:e.target.value})}><option value="">Leave unassigned</option>{eligible.map(m=><option key={m.id} value={m.user}>{m.user_name||m.user_email}</option>)}</select></label><label>Task title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Description<textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>{error&&<p className="form-error">{error}</p>}<button className="button primary full">Create task</button></form></article></section></>}
function TaskRows({tasks,user,refresh}){async function act(id,action){await api(`tasks/${id}/${action}/`,{method:'POST'});refresh?.()}return <div className="task-list">{tasks.map(t=><div className="task-row" key={t.id}><span><small>{t.key} · {t.assignment_status.replaceAll('_',' ')}</small><b>{t.title}</b></span><i>{t.status.replaceAll('_',' ')}</i><div>{t.assignee===user?.id&&t.assignment_status==='PENDING'&&<button onClick={()=>act(t.id,'accept')}>Accept</button>}{t.assignee===user?.id&&t.assignment_status==='ACCEPTED'&&t.status==='NOT_STARTED'&&<button onClick={()=>act(t.id,'start-work')}>Start work</button>}</div></div>)}</div>}

function UAT({user}){
  const [refresh,setRefresh]=useState(0),[assignment,setAssignment]=useState({task:'',user:'',is_main:true}),[observation,setObservation]=useState({task:'',title:'',description:'',severity:'MEDIUM'}),[error,setError]=useState('');
  const state=useLoad(async()=>({observations:list(await api('uat-observations/')),testing:list(await api('task-testers/')),tasks:list(await api('tasks/')),members:list(await api('project-members/'))}),[refresh]);
  if(state.loading)return <PageLoading/>;
  const selectedTask=state.data.tasks.find(t=>String(t.id)===String(assignment.task));
  const testers=state.data.members.filter(m=>selectedTask&&String(m.project)===String(selectedTask.project)&&m.role==='MEMBER'&&m.is_active);
  async function assign(e){e.preventDefault();setError('');try{await api('task-testers/',{method:'POST',body:JSON.stringify(assignment)});setRefresh(x=>x+1)}catch(e){setError(e.message)}}
  async function observe(e){e.preventDefault();setError('');try{await api('uat-observations/',{method:'POST',body:JSON.stringify(observation)});setObservation({...observation,title:'',description:''});setRefresh(x=>x+1)}catch(e){setError(e.message)}}
  async function accept(id){try{await api(`task-testers/${id}/accept/`,{method:'POST'});setRefresh(x=>x+1)}catch(e){setError(e.message)}}
  return <><PageTitle kicker="Quality control" title="UAT and observations" text="A tester must accept the testing assignment before recording an observation."/><section className="dashboard-grid"><article className="panel"><PanelHead title="Testing assignments"/>{state.data.testing.length?state.data.testing.map(x=><div className="simple-row" key={x.id}><b>{x.user_name||'Tester'}</b><span>{x.accepted_at?'Accepted':'Awaiting acceptance'}{x.is_main?' · Main tester':''}{x.user===user.id&&!x.accepted_at&&<button onClick={()=>accept(x.id)}>Accept</button>}</span></div>):<InlineEmpty text="No testing assignments."/>}<form onSubmit={assign}><h3>Assign a tester</h3><label>Task<select required value={assignment.task} onChange={e=>setAssignment({...assignment,task:e.target.value,user:''})}><option value="">Select task</option>{state.data.tasks.map(t=><option key={t.id} value={t.id}>{t.key} · {t.title}</option>)}</select></label><label>Tester<select required value={assignment.user} onChange={e=>setAssignment({...assignment,user:e.target.value})}><option value="">Select project member</option>{testers.map(m=><option key={m.id} value={m.user}>{m.user_name||m.user_email}</option>)}</select></label><label className="check"><input type="checkbox" checked={assignment.is_main} onChange={e=>setAssignment({...assignment,is_main:e.target.checked})}/> Main tester</label><button className="button primary full">Assign tester</button></form></article><article className="panel wide"><PanelHead title="Observations"/>{state.data.observations.length?state.data.observations.map(x=><div className="simple-row" key={x.id}><b>{x.title}</b><span>{x.severity} · {x.status.replaceAll('_',' ')}</span></div>):<InlineEmpty text="No UAT observations are visible to you."/>}<form onSubmit={observe}><h3>Raise an observation</h3><label>Accepted testing task<select required value={observation.task} onChange={e=>setObservation({...observation,task:e.target.value})}><option value="">Select task</option>{state.data.testing.filter(x=>x.user===user.id&&x.accepted_at).map(x=>{const t=state.data.tasks.find(t=>t.id===x.task);return t&&<option key={x.id} value={t.id}>{t.key} · {t.title}</option>})}</select></label><label>Title<input required value={observation.title} onChange={e=>setObservation({...observation,title:e.target.value})}/></label><label>Description<textarea required value={observation.description} onChange={e=>setObservation({...observation,description:e.target.value})}/></label><label>Severity<select value={observation.severity} onChange={e=>setObservation({...observation,severity:e.target.value})}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label><button className="button primary full">Raise observation</button></form></article>{error&&<p className="form-error">{error}</p>}</section></>}

function Leave(){const [refresh,setRefresh]=useState(0);const state=useLoad(async()=>({leave:list(await api('leave/')),projects:list(await api('projects/'))}),[refresh]);const [form,setForm]=useState({leave_type:'Annual leave',from_date:'',to_date:'',affected_projects:[]}),[error,setError]=useState('');if(state.loading)return <PageLoading/>;async function submit(e){e.preventDefault();try{await api('leave/',{method:'POST',body:JSON.stringify(form)});setRefresh(x=>x+1)}catch(e){setError(e.message)}}return <><PageTitle kicker="Availability" title="Leave and comp off" text="Your request records the impact across selected projects while keeping private reasons restricted."/><section className="dashboard-grid"><article className="panel wide"><PanelHead title="My requests"/>{state.data.leave.length?state.data.leave.map(x=><div className="simple-row" key={x.id}><b>{x.leave_type} · {x.from_date} to {x.to_date}</b><span>{x.status.replaceAll('_',' ')}</span></div>):<InlineEmpty text="No leave or comp-off requests yet."/>}</article><article className="panel"><PanelHead title="Apply"/><form onSubmit={submit}><label>Type<select value={form.leave_type} onChange={e=>setForm({...form,leave_type:e.target.value})}><option>Annual leave</option><option>Sick leave</option><option>Comp off</option></select></label><div className="two"><label>From<input required type="date" value={form.from_date} onChange={e=>setForm({...form,from_date:e.target.value})}/></label><label>To<input required type="date" value={form.to_date} onChange={e=>setForm({...form,to_date:e.target.value})}/></label></div><label>Affected projects<select multiple required value={form.affected_projects} onChange={e=>setForm({...form,affected_projects:[...e.target.selectedOptions].map(x=>x.value)})}>{state.data.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{error&&<p className="form-error">{error}</p>}<button className="button primary full">Submit request</button></form></article></section></>}

function PlatformAdmin({user}){const [refresh,setRefresh]=useState(0),[error,setError]=useState('');const state=useLoad(()=>api('platform-admin/summary/'),[refresh]);if(!user.is_staff)return <Empty title="Administrator access required" text="This area is restricted to authorized BQ Labs platform administrators."/>;if(state.loading)return <PageLoading/>;if(state.error)return <Empty title="Unable to load administration" text={state.error}/>;async function setUserStatus(id,is_active){setError('');try{await api(`platform-admin/users/${id}/status/`,{method:'POST',body:JSON.stringify({is_active})});setRefresh(x=>x+1)}catch(e){setError(e.message)}}return <><PageTitle kicker="BQ Labs platform control" title="Quantum OPS administration" text="Monitor account activity, workspace plan usage, and access status from one protected console."/><section className="metrics">{[['Registered users',state.data.users.length],['Active users',state.data.users.filter(x=>x.is_active).length],['Workspaces',state.data.organizations.length],['Starter plans',state.data.organizations.filter(x=>x.plan==='Starter').length]].map(x=><article key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></article>)}</section>{error&&<p className="form-error">{error}</p>}<section className="panel admin-panel"><PanelHead title="User access and activity"/><div className="table-scroll"><table><thead><tr><th>User</th><th>Last login</th><th>Tasks owned</th><th>Tasks assigned</th><th>Status</th><th>Action</th></tr></thead><tbody>{state.data.users.map(x=><tr key={x.id}><td><b>{x.name||x.email}</b><small>{x.email}</small></td><td>{x.last_login?new Date(x.last_login).toLocaleString():'Never'}</td><td>{x.owned_tasks}</td><td>{x.assigned_tasks}</td><td><span className={'status-pill '+(x.is_active?'good':'bad')}>{x.is_active?'Active':'Blocked'}</span></td><td><button disabled={x.id===user.id} onClick={()=>setUserStatus(x.id,!x.is_active)}>{x.is_active?'Block':'Restore'}</button></td></tr>)}</tbody></table></div></section><section className="panel admin-panel"><PanelHead title="Plans and quota usage"/><div className="table-scroll"><table><thead><tr><th>Workspace</th><th>Plan</th><th>Status</th><th>Users</th><th>Projects</th><th>Tasks</th></tr></thead><tbody>{state.data.organizations.map(x=><tr key={x.id}><td><b>{x.name}</b></td><td>{x.plan}</td><td>{x.status.replaceAll('_',' ')}</td><td>{x.users} / {x.user_limit}</td><td>{x.projects} / {x.project_limit}</td><td>{x.tasks} / {x.task_limit}</td></tr>)}</tbody></table></div></section></>}

function PageTitle({kicker,title,text,action,onAction}){return <div className="page-title"><div><small>{kicker}</small><h1>{title}</h1><p>{text}</p></div>{action&&<button className="button primary" onClick={onAction}>{action}</button>}</div>}
function PanelHead({title,action,onAction}){return <div className="panel-head"><h2>{title}</h2>{action&&<button onClick={onAction}>{action} →</button>}</div>}
function Empty({title,text,action,onAction}){return <div className="empty"><Mark/><h1>{title}</h1><p>{text}</p>{action&&<button className="button primary" onClick={onAction}>{action}</button>}</div>}
const InlineEmpty=({text})=><p className="inline-empty">{text}</p>;const PageLoading=()=> <div className="page-loading">Loading your authorized data…</div>;

function InvitationAccept(){const [message,setMessage]=useState('Checking your invitation…');useEffect(()=>{const token=new URLSearchParams(location.search).get('token')||'';api('auth/session/').then(()=>api('invitations/accept/',{method:'POST',body:JSON.stringify({token})})).then(()=>setMessage('Invitation accepted. Opening your dashboard…')).then(()=>setTimeout(()=>go(Q+'/dashboard'),900)).catch(e=>{if(e.status===403){const target=location.pathname+location.search;go(Q+'/login?return_to='+encodeURIComponent(target))}else setMessage(e.message)})},[]);return <div className="loading"><Mark/><span>{message}</span></div>}
export default function App(){const path=usePath();if(path==='/'||!path.startsWith(Q))return <Public/>;if(path===Q||path===Q+'/')return <Redirect to={Q+'/login'}/>;if(path===Q+'/login')return <Auth/>;if(path===Q+'/register')return <Auth register/>;if(path===Q+'/invitations/accept')return <InvitationAccept/>;const page=path.slice(Q.length+1).split('/')[0]||'dashboard';if(![...navItems,['admin']].some(x=>x[0]===page))return <Redirect to={Q+'/dashboard'}/>;return <Protected page={page}/>}
function Redirect({to}){useEffect(()=>go(to),[to]);return null}
